# Generated by Django 3.2.19 on 2023-07-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInformation',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
